#+title:  faq
#+SETUPFILE: ../org-templates/level-1.org

* Virtual Labs faq
  Virtual Labs are intended to augment the learning of
  science and engineering subjects through performing
  experiments. The experiments are designed either as
  simulations or as remote triggered. A remote triggered lab
  allows a user to connect to real equipment using a web
  browser. There are currently around 150 and labs and 1700+
  experiments at various stages of development and
  deployment. They are currently hosted at Vlabs. Virtual
  Labs is an initiative of Ministry of Human Resources,
  India.
  

** How can I request for a workshop to be conducted at my college

   You can request for a workshop to be conducted at your
   college by following the below steps :

   * Please make sure that the requirements are met.
   * Fill the [[https://docs.google.com/a/vlabs.ac.in/forms/d/e/1FAIpQLScvUGaE6ln6JzeIVc2CqTXwac_R69WhzoM5TrW6y99hFB6nbw/viewform?embedded=true][Expression of Interest]] form.
   * You would be contacted by the Virtual Labs Outreach Team.
   * On confirmation from the Virtual Labs team on the
     workshop date (as filled in the Expression of Interest)
     , you would need to download a checklist
     [form](./forms/Prerequisite-online-version-workshop.docx)
     You would then need to mail the duly fill/scanned form
     to [[mailto:workshops@vlabs.ac.in][workshops@vlabs.ac.in]].
   * On receipt of the above form, Virtual Labs Outreach
     Team would conduct the workshop on the scheduled date
     at your premises.

 


