#+title:  virtual-labs-workshop-faq
#+SETUPFILE: ../org-templates/level-1.org

**** Q01. What is a Virtual Labs Workshop?
  Virtual Labs Team organizes workshops with hands-on practice 
  sessions on Virtual Labs for interested Science & Engineering Institutions. 
  The sessions are conducted for faculty members and students of interested 
  institutes upon expression of their interest for Virtual Labs workshop.

**** Q02. Who can request for a Virtual Labs Workshop?
  Workshops can be requested by faculty members or
  college/institute management of the interested Science &
  Engineering Institutions.
  
**** Q03. Who can participate in the Workshop?
  All interested faculty and students of the
  college/institutes can participate in the workshop.
  
**** Q04. What are the modes of Virtual Labs Workshop?
  There are two modes of Virtual Labs Workshop - Onsite and Online.
  Onsite workshops are conducted in the premises of the college 
  requesting the workshop whereas online workshops as the name 
  suggests are conducted as webinars. 
  
**** Q05. What are the system requirements for a Onsite Virtual Lab Workshop?
  For a  Virtual Labs onsite workshop to be conducted, your
  college/institute would have to meet the following system
  requirements: System configuration (Recommended)

    - No pop-up blockers

    - A multimedia projector

    - Browser: Firefox, Chrome

    - Internet connection (2-4 Mbps)

    - Plugins: Flash, Java 1.6 version, and IcedTea

    - JavaScript should be enabled on the browser

**** Q06. What are the other requirements for a Onsite Virtual Labs Workshop?
  For a Virtual Labs workshop to be conducted , your
  college/institute would have to meet the following
  requirements:

    - [[http://vlab.co.in/][Virtual Labs]] web page should be accessible from the
      browser.

    - [[https://www.java.com/en/download/][Java]] must be downloadable through the Internet and
      Gmail must be accessible.

    - The college/institute should be a Central/State
      University or institute/college approved by AICTE/UGC.

    - For onsite workshops,the college/institute must have
      an auditorium with a seating capacity of at least 100
      and a designated/common lab space having 35 PCs or
      more.

    - In the event that the Internet operates behind a
      firewall, the specific communication ports 3306, 5900,
      5902, and 8700 would need to be opened to facilitate
      Virtual Labs network traffic.
      
**** Q07. What are the system requirements for a Online Virtual Lab Workshop?
  For a  Online Virtual Labs workshop to be conducted, your
  college/institute would have to meet the following system
  requirements: 
  
  - The institute should be a Central/State University or institute/college approved by AICTE/UGC.

  - A good Internet connection/link for each individual participant should be available.

  - Java must be downloadable through the Internet and Gmail should be accessible.

  - System configuration (Recommended) :

  - Browser: Firefox and Chrome.

  - Plugins: Flash, Java 1.6 version, and IcedTea.

  - JavaScript should be enabled on the browser.

  - No pop-up blockers.

**** Q08. How can I request for a workshop to be conducted at my college

   * Make sure that the requirements are met.

   * Fill the [[https://docs.google.com/a/vlabs.ac.in/forms/d/e/1FAIpQLScvUGaE6ln6JzeIVc2CqTXwac_R69WhzoM5TrW6y99hFB6nbw/viewform?embedded=true][Expression of Interest]] form.

   * Wait to be contacted by the Virtual Labs Outreach
     Team.

   * On confirmation from the Virtual Labs team on the
     workshop date (as filled in the Expression of
     Interest), download a checklist [[https://docs.google.com/document/d/1CvHfQTX331oEJlaXvQHaqjY2y8q_Esj5FFDs3hOG36Q/edit][form]]
     and  mail the duly fill/scanned form
     to [[mailto:ioc-iiith@vlabs.ac.in][ioc-iiith@vlabs.ac.in]]

   On receipt of the above form, Virtual Labs Outreach
     Team would conduct the online/Inperson workshop on the
     scheduled date.

**** Q09. What would be covered in the workshop?
  An overview, demo and hands-on of two Virtual Labs will be
  covered during the workshop.

**** Q10. Does my college have to pay for the workshops?
  College/Institute will have to pay for the travel, lodging
  and boarding for two Virtual Labs representatives for an 
  Onsite Workshop. Online workshops will not incur any expenditure 
  for the college/institute. 

**** Q11. Where can I get support on Virtual Labs Workshops?
  You can get help on workshops and other Virtual Labs
  related issues by posting on the mailing list for
  engineers contributing to Virtual Labs. You may
  [[https://groups.google.com/a/vlabs.ac.in/g/engineers?pli=1][Subscribe/Unsubscribe to the engineers]] mailing list. You
  can also post your queries to the [[https://currents.google.com/u/1/communities/104131148292250423165][teacher's community]].

**** Q12. What are the terms and conditions for using Virtual Labs in your college?
  There is no financial liability on any party for using
  Virtual Labs. It is free to use.

  * The Institute/College cannot charge students for the use
    of Virtual Labs.

  * The institute/college must nominate a single point of
    contact for all logistical and technical coordination
    between the institute and Virtual Labs.

**** Q13. Where have the Virtual Labs workshops been conducted?
  Please follow the [[http://outreach.vlabs.ac.in/ws_details#/ws-list][link]] to view the list of colleges where
  Virtual Labs Workshops have been conducted.
