#+title:  workshop-process
#+SETUPFILE: ../org-templates/level-1.org

* Virtual Labs Workshops
** Overview and Motivation 
  Virtual Labs Team organizes workshops and hands-on
  practice sessions on Virtual Labs (both online and In
  person) for interested Science & Engineering
  Institutions. Training sessions would be conducted for
  faculty members and students of interested institutes upon
  expression of their interest in Virtual Labs workshop.
  
  On the other hand the online version is available at all
  times but is dependent on a good Internet link. Any of the
  1700+ odd experiments could be performed at all times
  providing a good opportunity for continuous usage. Online
  versions should be used together in a college. On
  completion of the demonstrations and hands-on sessions,
  the faculty members and the students would be encouraged
  to submit the feedback form to the Virtual Labs
  team. These forms would be compiled and analyzed for
  further improvements in the Virtual Labs. 
** Audience 
   Workshops could be requested by faculty members or college
   management of the interested Science & Engineering Institutions.
   
** Requirements
*** Requirements for Online version 
    - The institute should be a Central/State University or
      institute/college approved by AICTE/UGC.

    - The institute must have an auditorium with a seating capacity of
      at least 100 and a designated/common lab space having 35 PCs or
      more.

    - In the event that the Internet operates behind a firewall, the
      specific communication ports 3306, 5900, 5902, and 8700 would
      need to be opened to facilitate Virtual Labs network
      traffic.

    - Java must be downloadable through the Internet and Gmail should
      be accessible.

      System configuration (Recommended) 
      
      - Browser: Firefox, Chrome

      - Plugins: Flash, Java 1.6 version, and IcedTea

      - JavaScript should be enabled on the browser

      - Internet connection (1 Mbps) and a multimedia
        projector

      - No pop-up blockers

    Pre-Workshop checklist
    
      - Vlabs web page should be accessible from the
        browser.

      - Registration should be successful from registration
        page.

      - Within a lab, lab-level and experiment-level
        feedback links should be working within the
        institute network.
    
*** Requirements for Inperson Workshops
    
** Request for Workshops
   Follow the steps below to have a workshop conducted at
   your college :
   
      1. Please make sure that the requirements (online
         version/Inperson) are met.

      2. Fill the Expression of Interest form.

      3. Virtual Labs Outreach Team would contact you in
         5-10 working days. Further communications would
         happen through email.

      4. On confirmation from the Virtual Labs team on the
         workshop date (as filled in the Expression of
         Interest) , a checklist form for online version and
         a checklist form for offline College Cloud version
         needs to be duly filled, scanned and mailed to
         workshops@vlabs.ac.in .

      5. On receipt of the above form, Virtual Labs Outreach
         Team would conduct the workshop on the scheduled
         date.


[[http://vlabs.ac.in:5959/faq/][Frequently Asked Questions]]

[[http://outreach.virtual-labs.ac.in/ws_details#ws-list][Past Workshops]]
