#+title:  workshop-process
#+SETUPFILE: ../org-templates/level-1.org

* Virtual Labs Workshops
** Overview and Motivation 
  Virtual Labs Team organizes workshops and hands-on
  practice sessions on Virtual Labs (both online and In
  person) for interested Science & Engineering
  Institutions. Training sessions would be conducted for
  faculty members and students of interested institutes upon
  the expression of their interest in Virtual Labs workshop.
  
  On the other hand the online version is available at all
  times but is dependent on a good Internet
  connection/link. Any of the 1700+ odd experiments could be
  performed at all times providing a good opportunity for
  continuous usage. Online versions should be used together
  in a college. On completion of the demonstrations and
  hands-on sessions, the faculty members and the students
  would be encouraged to submit the feedback form to the
  Virtual Labs team. These forms would be compiled and
  analyzed for further improvements in the Virtual Labs.
** Audience 
   Workshops could be requested by faculty members or college
   management of the interested Science & Engineering Institutions.
   
** Requirements
*** Requirements for Online version 
    - The institute should be a Central/State University or
      institute/college approved by AICTE/UGC.

    - Online workshop dependent on a good Internet
      connection/link for each individual participant.

    - Java must be downloadable through the Internet and Gmail should
      be accessible.

      System configuration (Recommended) 
      
      - Browser: Firefox and Chrome

      - Plugins: Flash, Java 1.6 version, and IcedTea

      - JavaScript should be enabled on the browser

      - No pop-up blockers

    Pre-Workshop checklist
    
      - Vlabs web page should be accessible from the
        browser.

      - Within a lab, lab-level and experiment-level
        feedback links should be working within the
        institute network.
    
*** Requirements for Inperson Workshops

    1. Students of II, III and IV years across all Engineering Deciplices.
    2. Number of student per session could be 30-60.
    3. System configuration (Recommended for each person)
         - Browser: Firefox and Chrome
         - Internet connection (4 Mbps) with Virtual labs web page accessible from the browser.
    4. One multimedia projector
    5. A lab accommodating the students, computers and projector.

    
** Request for Workshops
   Follow the steps below to have a workshop conducted at
   your college :
   
      1. Please make sure that the requirements
         (online/Inperson) are met.

      2. Fill the [[https://docs.google.com/forms/d/e/1FAIpQLScvUGaE6ln6JzeIVc2CqTXwac_R69WhzoM5TrW6y99hFB6nbw/viewform?embedded=true)+form.][Expression of Interest form]]

      3. Virtual Labs Outreach Team would contact you in
         5-10 working days. Further communications would
         happen through email.


      4. Virtual Labs Team will confirm the workshop date
         through email.

      5. On receipt of the above confirmation, Virtual Labs
         Outreach Team would conduct the workshop on the
         scheduled date.

